version: '3.8'

services:
  tfm_prg:
    image: pablorg:torch_latest
    command: /bin/bash
    container_name: tfm_prg
    ports:
      - "8888:8888"
    volumes:
      - /mnt/LVMData/Datasets/Tractoinferno/:/app/dataset/Tractoinferno
      - /mnt/LVMData/Datasets/HCP105_Zenodo_NewTrkFormat/:/app/dataset/HCP_105
      - /home/vvillena/tfm_prg/tfm_prg:/app
    deploy:
      resources:
        limits:
          memory: 15G
        reservations:
          memory: 14G
    environment:
      - NVIDIA_VISIBLE_DEVICES=all


    # Para que funcione correctamente, se debe ejecutar el siguiente comando en la terminal
    # docker-compose up -d (para ejecutar en segundo plano)
    # docker-compose ps (para ver los contenedores en ejecución)
    # docker-compose down (para detener los contenedores)
    # docker-compose logs (para ver los logs de los contenedores)
    # docker-compose exec tfm_prg /bin/bash (para acceder al contenedor)

